name: lapercuy
description: "lapercuy project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  carousel_slider: ^5.0.0
  readmore: ^2.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Library untuk Logo & Splash Screen
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Aset Gambar
  assets:
    - assets/images/

  # Konfigurasi Font Poppins
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

# ==========================================
# KONFIGURASI ICON & SPLASH SCREEN LAPERCUY
# ==========================================

# 1. Konfigurasi Icon Aplikasi
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_lapercuy.jpg"
  min_sdk_android: 21

# 2. Konfigurasi Splash Screen (Layar Awal)
flutter_native_splash:
  color: "#FFFFFF" # Background putih
  image: "assets/images/logo_lapercuy.jpg"
  android_12: # Khusus Android 12+
    image: "assets/images/logo_lapercuy.jpg"
    color: "#FFFFFF"